language: generic
python: 2.7.13
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-4.9
            - cmake-data
            - cmake
          install: 
            - export CXX="g++-4.9" CC="gcc-4.9"
      env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-5
            - cmake-data
            - cmake
          install: 
            - export CXX="g++-5" CC="gcc-5"
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-6
            - cmake-data
            - cmake
          install: 
            - export CXX="g++-6" CC="gcc-6"
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

install: 
  - pip install pyNN requests pyminifier numpy
script: 
  - mkdir build_gcc 
  - cd build_gcc 
  - cmake .. -DSTATIC_LINKING=FALSE
  - make && make test ARGS=-V
